BPA.UI.WEB/Controllers/AnsiraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPA.UI.WEB.Controllers
{
    public class AnsiraController : Controller
    {
        // GET: Ansira
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult HomePage()
        {
            return View();
        }
    }
}

BPA.UI.WEB/Controllers/BACKBONEController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPA.UI.WEB.Controllers
{
    public class BackboneController : Controller
    {
        // GET: Backbone
        public ActionResult BackboneIdentifier()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

BPA.UI.WEB/Controllers/BackbonePageElementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPA.UI.WEB.Controllers
{
    public class BackbonePageElementController : Controller
    {
        // GET: BackbonePageElement
        public ActionResult Index()
        {
            return View();
        }
    }
}

BPA.UI.WEB/Controllers/BackbonePageElementIdentifierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPA.UI.WEB.Controllers
{
    public class BackbonePageElementIdentifierController : Controller
    {
        // GET: BackbonePageElementIdentifier
        public ActionResult Index()
        {
            return View();
        }
    }
}

BPA.UI.WEB/Controllers/BackbonePageIdentifierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPA.UI.WEB.Controllers
{
    public class BackbonePageIdentifierController : Controller
    {
        // GET: BackbonePageIdentifier
        public ActionResult Index()
        {
            return View();
        }
    }
}

BPA.UI.WEB/Controllers/DataElementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPA.UI.WEB.Controllers
{
    public class DataElementController : Controller
    {
        // GET: DataElement
        public ActionResult Index()
        {
            return View();
        }
    }
}

BPA.UI.WEB/Controllers/PageTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPA.UI.WEB.Controllers
{
    public class PageTypeController : Controller
    {
        // GET: PageType
        public ActionResult PageType()
        {
            return View();
        }
        public ActionResult BackbonePage()
        {
            return View();
        }
        public ActionResult PageAnalysisPageElement()
        {
            return View();
        }
    }
}

BPA.UI.WEB/Views/Ansira/HomePage.cshtml
@{
    ViewBag.Title = "HomePage";
    Layout = "~/Views/Ansira/index.cshtml";
}

<h2>HomePage</h2>

BPA.UI.WEB/Views/Ansira/index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <!------ Include the above in your HEAD tag ---------->
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script language="JavaScript" src="https://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script language="JavaScript" src="https://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.css">
    <!--Validation links-->
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="@Url.Action("HomePage", "Ansira")">Anisra</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page Type<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("PageType", "PageType")">Page Type</a></li>
                            <li><a href="@Url.Action("BackbonePage", "PageType")">Backbone Page</a></li>
                            <li><a href="@Url.Action("Index", "BackbonePageIdentifier")">Backbone Page Identifier</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Backbone<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Backbone")">Backbone</a></li>
                            <li><a href="@Url.Action("BackboneIdentifier", "Backbone")">Backbone Identifier</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Data Element<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "DataElement")">Data Element</a></li>
                            <li><a href="@Url.Action("Index", "BackbonePageElement")">Backbone Page Element</a></li>
                            <li><a href="@Url.Action("Index", "BackbonePageElementIdentifier")">Backbone Page Element Identifier</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("PageAnalysisPageElement", "PageType")">Page Type Analysis</a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
            <label id="baseURL" hidden>@System.Configuration.ConfigurationManager.AppSettings["BaseURL"]</label>
            @RenderBody()
        </div>
    </div>
</body>
</html>

BPA.UI.WEB/Views/Backbone/BackboneIdentifier.cshtml
@{
    Layout = "~/Views/Ansira/index.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BackboneIdentifier</title>
    <script src="~/script/backboneIdentifier.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <h2 class="text-center">Backbone Identifiers</h2>
            <button class="btn btn-primary" data-title="Create" data-toggle="modal" data-target="#create"><span>Create Backbone Identifier</span></button>
        </div>
        <div class="row" style="margin-top:10px;">
            <div class="col-md-12">
                <table id="BackboneIdentifierDataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Backbone</th>
                            <th>Type</th>
                            <th>Identifier</th>
                            <th>SerialNo</th>
                            <th>Value</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>

            </div>
        </div>

        <div class="modal fade" id="create" tabindex="-1" role="dialog" aria-labelledby="create" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title custom_align" id="Heading">Create Backbone Identifier Data</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <select class="form-control" id="selectBackboneId">
                                <option value="0">Select Backbone Id</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtType" type="text" placeholder="Type" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtIdentifier" type="text" placeholder="Identifier" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtSerialNo" type="text" placeholder="SerialNo" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtValue" type="text" placeholder="Value" />
                        </div>
                    </div>
                    <div class="modal-footer ">
                        <button type="button" onclick="createBackboneIdentifier()" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span>Create</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>

        <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title custom_align" id="Heading">Edit Your Detail</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <select class="form-control" id="selectedtBackboneId">
                                <option value="0">Select Backbone Id</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtedtType" type="text" placeholder="Type" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtedtIdentifier" type="text" placeholder="Identifier" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtedtSerialNo" type="text" placeholder="SerialNo" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="txtedtValue" type="text" placeholder="Value" />
                        </div>
                        <div>
                            <span id="lableBackboneIdentifierId" hidden></span>
                        </div>
                    </div>
                    <div class="modal-footer ">
                        <button type="button" onclick="updateBackboneIdentifier()" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span> Update</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>

        <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title custom_align" id="Heading">Delete this entry</h4>
                    </div>
                    <div class="modal-body">
                        <span id="labledeleteBackboneIdentifierId" hidden></span>
                        <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> Are you sure you want to delete this Record?</div>

                    </div>
                    <div class="modal-footer ">
                        <button type="button" onclick="deleteBackboneIdentifier()" class="btn btn-success"><span class="glyphicon glyphicon-ok-sign"></span> Yes</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
                    </div>


                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div> 
    </div>
</body>
</html>

BPA.UI.WEB/Views/Backbone/Index.cshtml
@{
    Layout = "~/Views/Ansira/index.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/script/backbone.js"></script>   
    <title>Backbone</title>
    </head>
<body>
    <div class="row">
        <h2 class="text-center">Backbones</h2>
        <button class="btn btn-primary" data-title="Create" data-toggle="modal" data-target="#create"><span>Create Backbone</span></button>
    </div>
    <div class="row" style="margin-top:10px;">
        <div class="col-md-12">
            <table id="Backbonedatatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
              
            </table>

        </div>
    </div>

    <div class="modal fade" id="create" tabindex="-1" role="dialog" aria-labelledby="create" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title custom_align" id="Heading">Create DEALER Data</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input class="form-control" id="txt_Backbone_Name" type="text" placeholder="Backbone Name" />
                    </div>

                  
                </div>
                <div class="modal-footer ">
                    <button type="button" onclick="CreateBackboneData()" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span>Create</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title custom_align" id="Heading">Edit Your Detail</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input class="form-control" id="txt_Backbone_Name_Update" type="text" placeholder="Backbone Name" />
                    </div>

                    <div>
                        <span id="label_BackboneID" hidden></span>
                    </div>
                </div>
                <div class="modal-footer ">
                    <button type="button" onclick="UpdateBackboneData()" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span> Update</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title custom_align" id="Heading">Delete this entry</h4>
                </div>
                <div class="modal-body">
                    <span id="label_BackboneID_Delete" hidden></span>
                    <div class="alert alert-danger" id="txt_Backbone_Name_Delete"><span class="glyphicon glyphicon-warning-sign"></span> Are you sure you want to delete this Record?</div>

                </div>
                <div class="modal-footer ">
                    <button type="button" onclick="DeleteBackboneData()" class="btn btn-success"><span class="glyphicon glyphicon-ok-sign"></span> Yes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
                </div>


            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
</body>
</html>

BPA.UI.WEB/Views/BackbonePageElement/Index.cshtml
@{
    Layout = "~/Views/Ansira/index.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/script/backbonepageelement.js"></script>
    <title>Backbone Page Element</title>
</head>
<body>
    <div class="row">
        <h2 class="text-center" >Backbone Page Elements</h2>
        <button class="btn btn-primary" data-title="Create" data-toggle="modal" data-target="#create"><span>Create Backbone Page Element</span></button>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <table id="BackbonePageElementdatatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                       @* <th>Backbone</th>*@
                        <th>Page</th>
                        <th>Data Element</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>

        </div>
    </div>

    <div class="modal fade" id="create" tabindex="-1" role="dialog" aria-labelledby="create" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title custom_align" id="Heading">Create BackbonePage Element Data</h4>
                </div>
                <div class="modal-body">
                    @*<div class="form-group">
                        <input class="form-control" id="txt_Dealer_Name" type="text" placeholder="Dealer Name" />
                    </div>*@

                    @*Dropdown Here*@
                    <div class="form-group">
                        <select id="dropdownBackboneList" class="form-control">
                            <option value="0">Select Backbone</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <select id="dropdownBackbonePageList" class="form-control">
                            <option value="0">Select BackbonePage</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <select id="dropdownDataElementList" class="form-control">
                            <option value="0">Select DataElementType</option>
                        </select>
                    </div>


                </div>
                <div class="modal-footer ">
                    <button type="button" onclick="CreateBackbonePageElementData()" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span>Create</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title custom_align" id="Heading">Edit Your Detail</h4>
                </div>
                <div class="modal-body">
                    @*<div class="form-group">
                        <input class="form-control" id="txt_Dealer_Name_Update" type="text" placeholder="Dealer Name" />
                    </div>

                    <div class="form-group">
                        <input class="form-control" id="txt_Dealer_Url_Update" type="text" placeholder="Dealer URL" />
                    </div>*@

                    @*Dropdown Here*@
                    <div class="form-group">
                        <select id="dropdownBackbonePageListedt" class="form-control">
                            <option value="0">Select BackbonePage</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <select id="dropdownDataElementListedt" class="form-control">
                            <option value="0">Select DataElementType</option>
                        </select>
                    </div>

                    <div>
                        <span id="label_BackbonePageElementID" hidden></span>
                    </div>
                </div>
                <div class="modal-footer ">
                    <button type="button" onclick="UpdateBackbonePageElementData()" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span> Update</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title custom_align" id="Heading">Delete this entry</h4>
                </div>
                <div class="modal-body">
                    <span id="label_BackbonePageElementID_Delete" hidden></span>
                    <div class="alert alert-danger" id="txt_BackbonePageElement_Delete"><span class="glyphicon glyphicon-warning-sign"></span> Are you sure you want to delete this Record?</div>

                </div>
                <div class="modal-footer ">
                    <button type="button" onclick="DeleteBackbonePageElementData()" class="btn btn-success"><span class="glyphicon glyphicon-ok-sign"></span> Yes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
                </div>


            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
</body>
</html>

BPA.UI.WEB/Views/DataElement/Index.cshtml
@{
    Layout = "~/Views/Ansira/index.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/script/dataelement.js"></script>
    <title>Index</title>
</head>
<body>
    <div class="row">
        <h2 class="text-center">Data Elements</h2>
        <button class="btn btn-primary" data-title="Create" data-toggle="modal" data-target="#create"><span>Create Data Element</span></button>
    </div>
    <div class="row" style="margin-top:10px;">
        <div class="col-md-12">
            <table id="DataElementdatatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Data Element</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>

            </table>

        </div>
    </div>

    <div class="modal fade" id="create" tabindex="-1" role="dialog" aria-labelledby="create" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title custom_align" id="Heading">Create DataElement Data</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input class="form-control" id="txt_DataElement_Name" type="text" placeholder="DataElement Name" />
                    </div>


                </div>
                <div class="modal-footer ">
                    <button type="button" onclick="CreateDataElementData()" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span>Create</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title custom_align" id="Heading">Edit Your Detail</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input class="form-control" id="txt_DataElement_Name_Update" type="text" placeholder="DataElement Name" />
                    </div>

                    <div>
                        <span id="label_DataElementID" hidden></span>
                    </div>
                </div>
                <div class="modal-footer ">
                    <button type="button" onclick="UpdateDataElementData()" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span> Update</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title custom_align" id="Heading">Delete this entry</h4>
                </div>
                <div class="modal-body">
                    <span id="label_DataElementID_Delete" hidden></span>
                    <div class="alert alert-danger" id="txt_Backbone_Name_Delete"><span class="glyphicon glyphicon-warning-sign"></span> Are you sure you want to delete this Record?</div>

                </div>
                <div class="modal-footer ">
                    <button type="button" onclick="DeleteDataElementData()" class="btn btn-success"><span class="glyphicon glyphicon-ok-sign"></span> Yes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
                </div>


            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
</body>
</html>